# Site settings
title: "ProData Projekt"
description: "Prozessketten-übergreifende Detektion von Material- und Prozessanomalien bei Imbalanced Data für technische Kunststoffbaugruppen"
url: "https://institute-of-production-systems.github.io"
baseurl: "/prodata"

# CRITICAL: Theme and plugins for GitHub Pages
remote_theme: "mmistakes/minimal-mistakes"

# CRITICAL: Required plugins for GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji
  - jekyll-algolia

# GitHub Pages safe plugins
whitelist:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji
  - jekyll-algolia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /news/page:num/
timezone: Europe/Berlin

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      toc: true
      toc_sticky: true

# Project specific data
project:
  foerderkennzeichen: "16DKWN119A"
  funding_program: "Stärkung der Datenkompetenzen des wissenschaftlichen Nachwuchses"
  start_date: "2022"
  end_date: "2025"
  partners:
    - name: "RIF Institut für Forschung und Transfer e.V."
      location: "Dortmund"
      leader: "Prof. Dr.-Ing. Jochen Deuse"
      url: "https://www.rif-ev.de/"
      email: "deuse@rif-ev.de"
    - name: "Institut für Werkstofftechnik, Universität Kassel"
      location: "Kassel"
      leader: "Prof. Dr.-Ing. Hans-Peter Heim"
      url: "https://www.uni-kassel.de/maschinenbau/institute/werkstofftechnik"
      email: "heim@uni-kassel.de"

# Navigation
navigation:
  - title: "Start"
    url: "/"
  - title: "Forschung"
    url: "/research/"
  - title: "Partner"
    url: "/partners/"
  - title: "News"
    url: "/news/"
  - title: "Veröffentlichungen"
    url: "/publications/"
  - title: "Kontakt"
    url: "/contact/"